### PR TITLE
Clarify dual licensing with the maintenance license

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
I like it, it's pretty thorough, and I thought we should push for open licensing more, hence this proposal. 

People could also include their own additions, say if they didn't want to allow inclusion in other work, but I don't think we need to complicate matters.

### CODE REVIEW

**Review by mike1072 — CHANGES_REQUESTED** [review]
If a mod allowed sharing and adapting, it would indeed permit people to perform maintenance updates, but it would also allow them to perform other types of updates (new/changed content) and use the mod content in other projects.

I didn't want to to tie those things together, so I introduced the MAINTENANCE.md file to provide specific maintenance permissions which apply on top of whatever permissions are provided in the license.  This lets authors easily signal their approval for maintenance updates without handing over any permissions they're not comfortable with.  I may need to update the documentation to make that more clear.

I think it would be a good idea to suggest that people choose a permissive license when they want others to be able to expand on their work, especially if they aren't able to continue working on the project themselves.

**Comment by lynxlynxlynx** [comment]
Then there needs to be an extra clause somewhere, otherwise the two things are in conflict. It's not just CC anymore.

**Comment by mike1072** [comment]
I guess our use would be dual-licensing: the first license is the one specified in the LICENSE file and the second license is the simple one specified in MAINTENANCE.md.

Perhaps we should rename the LICENSE files to LICENSE-CC-BY-4.0 (etc.) and the MAINTENANCE.md file to LICENSE-MAINTENANCE.md to make this clearer and update the readme to indicate such.

e.g.

> This mod is Copyright (c) 2019 Author.  You are allowed to submit **maintenance updates** for this mod. _(linking LICENSE-MAINTENANCE.md)_ This mod is additionally licensed under **CC-BY-NC-4.0**, which grants additional permissions. _(linking the human-readable summary of the appropriate license on creativecommons.org)_

**Comment by lynxlynxlynx** [comment]
Yes, it would be dual-licensing. The renaming is a good idea for clarity and for non-ND licenses LICENSE-MAINTENANCE.md wouldn't even be needed.

**Review by mike1072 — APPROVED** [review]

**Comment by lynxlynxlynx** [comment]
Btw, do you plan to make any announcements? Existing mods could adopt these too.

**Comment by mike1072** [comment]
Yeah, I just wanted to make sure the recommendations were clear and provide some sample repos to point to before posting in the forums.  So far, just the RealMod repo has been updated.  I'll take a look at some of the other repos this weekend.

**Comment by mike1072** [comment]
Thanks for your engagement on this topic, by the way. It's been very helpful and motivating.

**Comment by lynxlynxlynx** [comment]
Gladly, I want mods to be resilient as much, if not more, as anyone.

Github nicely provides an overview of each license, however it appears it either doesn't support CC or there is extra text in our copies. Here's an example of gemrb-mods: https://github.com/lynxlynxlynx/gemrb-mods/blob/master/COPYING

**Comment by mike1072** [comment]
Yes, I was very interested in that feature.  Unfortunately, the software that detects the licenses ([licensee](https://github.com/licensee/licensee)) only attempts to detect [licenses that are described on choosealicense.com](https://choosealicense.com/appendix/).  Right now this is only CC0, CC-BY, and CC-BY-SA, and none of the other Creative Commons licenses.  They were traditionally focused on software licenses and have been very slow to adapt to increasing use of GitHub for other content.  There have been [requests to add all Creative Commons licenses](https://github.com/github/choosealicense.com/pull/86) going back 6 years now.

There's currently a 2-year old [bug](https://github.com/licensee/licensee/issues/243) in licensee where it doesn't properly detect official CC0 licenses as well.  The text for the CC0 license on choosealicense.com differs slightly from the official text on creativecommons.org, and licensee only correctly identifies the choosealicense.com version.

So, it's a bit of a mess.  I've just done some testing and it seems that if you have 2 files that start with LICENSE and they are detected as different licenses (or can't be identified), it won't display the nice summary for the repo with what it does detect.  Do you think we should change the naming of the maintenance file from LICENSE-MAINTENANCE.md to something like MAINTENANCE-NOTICE.md in case they sort out CC detection in the future?

**Comment by lynxlynxlynx** [comment]
I didn't look into it at all, but yeah, now would be the time to change the names if ever. MAINTENANCE-NOTICE also sounds less scary.

**Pull request merged**
